# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"

[version]
current = "0.2.4"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>wip|alpha|beta|rc|RC)
    (?P<release>\d+)
  )?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "wagtail_neuralyzer/__init__.py"

[[file]]
src = "pyproject.toml"
